"""Default folders and commands seeded into an empty store.

Carried over from sshpilot's command blocks. These are ordinary local-shell
commands; the ``${HOST}``/``${PID}``/``${SERVICE}`` entries demonstrate the
placeholder-substitution flow.
"""

DEFAULT_FOLDERS = [
    {"id": "f-sysinfo",  "name": "System Info", "parent_id": None, "order": 0, "expanded": True},
    {"id": "f-network",  "name": "Network",      "parent_id": None, "order": 1, "expanded": True},
    {"id": "f-procs",    "name": "Processes",    "parent_id": None, "order": 2, "expanded": True},
    {"id": "f-docker",   "name": "Docker",       "parent_id": None, "order": 3, "expanded": False},
    {"id": "f-systemd",  "name": "Systemd",      "parent_id": None, "order": 4, "expanded": False},
    {"id": "f-disk",     "name": "Disk",         "parent_id": None, "order": 5, "expanded": False},
    {"id": "f-logs",     "name": "Logs",         "parent_id": None, "order": 6, "expanded": False},
    {"id": "f-security", "name": "Security",     "parent_id": None, "order": 7, "expanded": False},
]

DEFAULT_COMMANDS = [
    # System Info
    {"id": "c-uname",    "name": "Kernel info",         "command": "uname -a",
     "description": "Kernel & architecture", "tags": ["system"], "folder_id": "f-sysinfo",
     "is_favorite": True, "has_placeholders": False},
    {"id": "c-osrel",    "name": "OS release",           "command": "cat /etc/os-release",
     "description": "Distribution details", "tags": ["system"], "folder_id": "f-sysinfo",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-uptime",   "name": "Uptime",               "command": "uptime -p",
     "description": "System uptime", "tags": ["system"], "folder_id": "f-sysinfo",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-mem",      "name": "Memory usage",         "command": "free -h",
     "description": "RAM & swap usage", "tags": ["system", "resources"], "folder_id": "f-sysinfo",
     "is_favorite": False, "has_placeholders": False},
    # Network
    {"id": "c-iface",    "name": "Network interfaces",   "command": "ip addr show",
     "description": "All interfaces and IPs", "tags": ["network"], "folder_id": "f-network",
     "is_favorite": True, "has_placeholders": False},
    {"id": "c-sockets",  "name": "Listening sockets",    "command": "ss -tulnp",
     "description": "Open ports & services", "tags": ["network", "ports"], "folder_id": "f-network",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-pubip",    "name": "Public IP",            "command": "curl -s ifconfig.me",
     "description": "Show public IP address", "tags": ["network"], "folder_id": "f-network",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-ping",     "name": "Ping host",            "command": "ping -c 4 ${HOST}",
     "description": "Ping a host 4 times", "tags": ["network"], "folder_id": "f-network",
     "is_favorite": False, "has_placeholders": True},
    # Processes
    {"id": "c-cpu-top",  "name": "Top CPU processes",    "command": "ps aux --sort=-%cpu | head -20",
     "description": "20 most CPU-hungry processes", "tags": ["processes", "resources"], "folder_id": "f-procs",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-proc-snap", "name": "Process snapshot",    "command": "top -bn1 | head -30",
     "description": "One-shot top output", "tags": ["processes"], "folder_id": "f-procs",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-kill",     "name": "Force kill PID",       "command": "kill -9 ${PID}",
     "description": "Kill process by PID", "tags": ["processes"], "folder_id": "f-procs",
     "is_favorite": False, "has_placeholders": True},
    # Docker
    {"id": "c-dps",      "name": "List containers",      "command": "docker ps -a",
     "description": "All Docker containers", "tags": ["docker"], "folder_id": "f-docker",
     "is_favorite": True, "has_placeholders": False},
    {"id": "c-dimages",  "name": "List images",          "command": "docker images",
     "description": "Local Docker images", "tags": ["docker"], "folder_id": "f-docker",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-dlogs",    "name": "Container logs",       "command": "docker logs --tail 100 -f ${CONTAINER}",
     "description": "Follow container logs", "tags": ["docker", "logs"], "folder_id": "f-docker",
     "is_favorite": False, "has_placeholders": True},
    {"id": "c-dexec",    "name": "Shell into container", "command": "docker exec -it ${CONTAINER} /bin/bash",
     "description": "Interactive shell in container", "tags": ["docker"], "folder_id": "f-docker",
     "is_favorite": False, "has_placeholders": True},
    {"id": "c-dstats",   "name": "Container stats",      "command": "docker stats --no-stream",
     "description": "Resource usage per container", "tags": ["docker", "resources"], "folder_id": "f-docker",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-dprune",   "name": "Prune Docker",         "command": "docker system prune -f",
     "description": "Remove unused Docker resources", "tags": ["docker"], "folder_id": "f-docker",
     "is_favorite": False, "has_placeholders": False},
    # Systemd
    {"id": "c-svc-stat", "name": "Service status",       "command": "systemctl status ${SERVICE}",
     "description": "Status of a systemd service", "tags": ["systemd", "services"], "folder_id": "f-systemd",
     "is_favorite": True, "has_placeholders": True},
    {"id": "c-svc-log",  "name": "Service logs",         "command": "journalctl -u ${SERVICE} -n 100 --no-pager",
     "description": "Last 100 lines of service journal", "tags": ["systemd", "logs"], "folder_id": "f-systemd",
     "is_favorite": False, "has_placeholders": True},
    {"id": "c-svc-fail", "name": "Failed units",         "command": "systemctl list-units --state=failed",
     "description": "All failed systemd units", "tags": ["systemd"], "folder_id": "f-systemd",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-svc-rst",  "name": "Restart service",      "command": "systemctl restart ${SERVICE}",
     "description": "Restart a systemd service", "tags": ["systemd", "services"], "folder_id": "f-systemd",
     "is_favorite": False, "has_placeholders": True},
    # Disk
    {"id": "c-df",       "name": "Disk usage",           "command": "df -h",
     "description": "Disk usage by mount point", "tags": ["disk"], "folder_id": "f-disk",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-du-logs",  "name": "Log dir sizes",        "command": "du -sh /var/log/*",
     "description": "Size of each log file/dir", "tags": ["disk", "logs"], "folder_id": "f-disk",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-lsblk",    "name": "Block devices",        "command": "lsblk",
     "description": "List all block devices", "tags": ["disk"], "folder_id": "f-disk",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-bigfiles", "name": "Largest files",
     "command": "find / -xdev -size +100M -printf '%s %p\\n' 2>/dev/null | sort -rn | head -10",
     "description": "Files over 100 MB", "tags": ["disk"], "folder_id": "f-disk",
     "is_favorite": False, "has_placeholders": False},
    # Logs
    {"id": "c-syslog",   "name": "Follow syslog",        "command": "tail -f /var/log/syslog",
     "description": "Live syslog (Ctrl+C to stop)", "tags": ["logs"], "folder_id": "f-logs",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-journal",  "name": "Follow journal",       "command": "journalctl -f -n 50",
     "description": "Live systemd journal", "tags": ["logs", "systemd"], "folder_id": "f-logs",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-errlogs",  "name": "Recent errors",        "command": "grep -i error /var/log/syslog | tail -50",
     "description": "Last 50 error lines in syslog", "tags": ["logs"], "folder_id": "f-logs",
     "is_favorite": False, "has_placeholders": False},
    # Security
    {"id": "c-last",     "name": "Recent logins",        "command": "last -n 20",
     "description": "Last 20 login events", "tags": ["security"], "folder_id": "f-security",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-who",      "name": "Who is logged in",     "command": "who",
     "description": "Currently logged-in users", "tags": ["security"], "folder_id": "f-security",
     "is_favorite": False, "has_placeholders": False},
    {"id": "c-lastb",    "name": "Failed logins",        "command": "lastb | head -20",
     "description": "Last 20 failed login attempts", "tags": ["security"], "folder_id": "f-security",
     "is_favorite": False, "has_placeholders": False},
]
